Repository UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend, pull requests merged in 2021-10, with the labels that each got.

#29 Página Pedido
  frontend/src/pages/Pedido/index.tsx
  frontend/src/pages/Pedido/styles.ts
  frontend/src/routes/index.tsx
  frontend/src/styles/global.ts
  frontend/src/styles/taNaMesaDarkTheme.ts
  frontend/src/styles/taNaMesaTheme.ts
Labels: feature, client

#32 Adiciona tela de Menu
  frontend/.env
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/assets/Menu/sem-items.png
  frontend/src/assets/sem-foto.jpg
  frontend/src/components/BackgroundHamburguer/index.tsx
  frontend/src/components/BackgroundHamburguer/styles.ts
  frontend/src/components/Button/styles.ts
  frontend/src/components/Loading/styles.ts
  frontend/src/components/MenuItem/index.tsx
  frontend/src/components/MenuItem/styles.ts
  frontend/src/components/SideBar/index.tsx
  frontend/src/components/SideBar/sideBarObjects/homeButtons.ts
  frontend/src/components/SideBar/sideBarObjects/menuUserButtons.ts
  frontend/src/components/SideBar/styles.ts
  frontend/src/components/SideBarButton/index.tsx
  frontend/src/components/SideBarButton/styles.ts
  frontend/src/hooks/index.tsx
  frontend/src/hooks/menu.tsx
  frontend/src/hooks/screen.tsx
  frontend/src/hooks/theme.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/styles.ts
  frontend/src/pages/Kitchen/index.tsx
  frontend/src/pages/Manager/index.tsx
  frontend/src/pages/Menu/index.tsx
  frontend/src/pages/Menu/styles.ts
  frontend/src/pages/Waiter/index.tsx
  frontend/src/services/items.ts
  frontend/src/styles/global.ts
  frontend/src/styles/taNaMesaDarkTheme.ts
  frontend/src/styles/taNaMesaTheme.ts
  frontend/yarn.lock
Labels: bug, feature, client

#40 (#38) ajustando imagens para arquivo assets
  frontend/src/components/BackgroundHamburguer/index.tsx
  frontend/src/components/BackgroundHamburguer/styles.ts
  frontend/src/components/MenuItem/index.tsx
  frontend/src/components/Modal/ComandaModal/index.tsx
  frontend/src/components/SideBar/index.tsx
  frontend/src/components/SideBar/sideBarObjects/homeButtons.ts
  frontend/src/components/SideBar/sideBarObjects/kitchenOptions.ts
  frontend/src/components/SideBar/sideBarObjects/managerOptions.ts
  frontend/src/components/SideBar/sideBarObjects/menuUserButtons.ts
  frontend/src/components/SideBar/sideBarObjects/waiterOptions.ts
  frontend/src/pages/Menu/index.tsx
  frontend/src/utils/assets.ts
Labels: Hacktoberfest, hacktoberfest-accepted
