Repository UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend, pull requests merged in 2021-09, with the labels that each got.

#3 Atualizando estrutura do Frontend
  .dockerignore
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  frontend/.editorconfig
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/config-overrides.js
  frontend/jest.config.js
  frontend/package.json
  frontend/prettier.config.js
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/App.tsx
  frontend/src/__tests__/pages/App.test.tsx
  frontend/src/assets/.gitkeep
  frontend/src/components/.gitkeep
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/styles.ts
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.js
  frontend/src/routes/index.tsx
  frontend/src/services/.gitkeep
  frontend/src/setupTests.ts
  frontend/src/styles/global.ts
  frontend/src/utils/.gitkeep
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: devops

#7 Cria gerenciador de estado do tema
  frontend/package.json
  frontend/src/@types/index.d.ts
  frontend/src/@types/styled-components.d.ts
  frontend/src/App.tsx
  frontend/src/hooks/index.tsx
  frontend/src/hooks/theme.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/styles.ts
  frontend/src/styles/taNaMesaDarkTheme.ts
  frontend/src/styles/taNaMesaTheme.ts
Labels: feature

#21 Refatoração da NavBar
  frontend/package.json
  frontend/src/components/Loading/styles.ts
  frontend/src/components/NavBar/FifthNavBar/index.tsx
  frontend/src/components/NavBar/FourthNavBar/index.tsx
  frontend/src/components/NavBar/SecondNavBar/index.tsx
  frontend/src/components/NavBar/ThirdNavBar/index.tsx
  frontend/src/components/NavBar/index.tsx
  frontend/src/components/NavBar/styles.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/styles.ts
  frontend/yarn.lock
Labels: feature

#23 Componente de Botão
  frontend/src/__tests__/components/Button/Button.test.tsx
  frontend/src/__tests__/components/NavBar.test.tsx
  frontend/src/__tests__/pages/App.test.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Button/styles.ts
  frontend/src/pages/Home/index.tsx
Labels: client

#25 Adiciona SideBar da aplicação com algumas páginas
  frontend/src/assets/SideBar/duvida 1.png
  frontend/src/assets/SideBar/simbolo batata 1.png
  frontend/src/assets/SideBar/simbolo_bebida 1.png
  frontend/src/assets/SideBar/simbolo_cardapio 1.png
  frontend/src/assets/SideBar/simbolo_conta 1.png
  frontend/src/assets/SideBar/simbolo_pedir 1.png
  frontend/src/assets/SideBar/simbolo_sobremesa 1.png
  frontend/src/assets/SideBar/simbolo_usuario 2.png
  frontend/src/assets/SideBar/smbolo_hamburguer 1.png
  frontend/src/assets/SideBar/visualizar_pedido 1.png
  frontend/src/assets/hamburguer-background.png
  frontend/src/assets/logo-contorno.png
  frontend/src/assets/logo-dagua.png
  frontend/src/components/BackgroundHamburguer/index.tsx
  frontend/src/components/BackgroundHamburguer/styles.ts
  frontend/src/components/SideBar/index.tsx
  frontend/src/components/SideBar/sideBarObjects/homeButtons.ts
  frontend/src/components/SideBar/sideBarObjects/index.ts
  frontend/src/components/SideBar/sideBarObjects/kitchenOptions.ts
  frontend/src/components/SideBar/sideBarObjects/managerOptions.ts
  frontend/src/components/SideBar/sideBarObjects/menuUserButtons.ts
  frontend/src/components/SideBar/sideBarObjects/waiterOptions.ts
  frontend/src/components/SideBar/styles.ts
  frontend/src/components/SideBarButton/index.tsx
  frontend/src/components/SideBarButton/styles.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/styles.ts
  frontend/src/pages/Kitchen/index.tsx
  frontend/src/pages/Kitchen/styles.ts
  frontend/src/pages/Manager/index.tsx
  frontend/src/pages/Manager/styles.ts
  frontend/src/pages/Menu/index.tsx
  frontend/src/pages/Menu/styles.ts
  frontend/src/pages/Waiter/index.tsx
  frontend/src/pages/Waiter/styles.ts
  frontend/src/routes/index.tsx
  frontend/src/styles/global.ts
  yarn.lock
Labels: feature, client

#31 Cria checkbox e estilos
  frontend/src/__tests__/components/Checkbox/Checkbox.test.tsx
  frontend/src/components/Checkbox/index.tsx
  frontend/src/components/Checkbox/styles.ts
Labels: feature
